### ISSUE TITLE
Implementar el método getTweetfonyUser($id)

### ISSUE THREAD

**Issue by sambrista** [AlbertoArraz/tweetfony#2]

**Comment by sambrista** [comment]
No veo que lo tengas hecho.

**Comment by AlbertoArraz** [comment]
Ahora si esta hecho

**Comment by sambrista** [comment]
Fíjate que cuando hacemos una petición GET a ``/api/tweets/{$id]`` obtenemos, además de los datos del tweet, el endpoint del usuario autor del tweet y una lista de endpoints de usuarios a los que les gusta el tweet (los likes).

Además de devolver el nombre del usuario y su username, devuelve también una lista de endpoints de sus tweets y una lista de endpoints de los tweets que le han gustado (likes).

**Comment by AlbertoArraz** [comment]
Revisar

**Comment by sambrista** [comment]
Comprobado.
