### ISSUE TITLE
Implementar GET /api/tweets y GET /api/users

### ISSUE THREAD

**Issue by sambrista** [AlbertoArraz/tweetfony#3]
Crea las rutas api_get_tweets y api_get_users para las peticiones GET en /tweets y /users que devuelvan un listado de enlaces a los tweets y usuarios.

**Comment by sambrista** [comment]
No veo que lo tengas hecho

**Comment by AlbertoArraz** [comment]
Revisar

**Comment by sambrista** [comment]
Comprobado.
